name: apk_tb_care
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  google_fonts: ^6.1.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  sqflite: ^2.4.2
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  permission_handler: ^12.0.0+1
  fl_chart: ^1.0.0
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
